# Defines when the pipeline is triggered
trigger:
- master
- v1.2.0
- cm-derivatives

# Jobs
jobs:

  # Linux job
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      python36:
        python.version: '3.6'
      python37:
        python.version: '3.7'
      python38:
        python.version: '3.8'
  steps:
  - checkout: self
    displayName: 'Checking out git repository'
    submodules: true
    persistCredentials: true
    clean: true
    
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'

  - script: |
      cd $(Build.Repository.LocalPath)/CI && ./devtools.sh
    displayName: 'Install development tools'

  - script: |
      cd $(Build.Repository.LocalPath)/CI && ./lint.sh
    displayName: 'Lint code'

  - script: |
      cd $(Build.Repository.LocalPath)/CI && ./build.sh
    displayName: 'Build package'
    condition: always()

  - script: |
      cd $(Build.Repository.LocalPath)/CI && ./test.sh
    displayName: 'Run regression tests'
    condition: always()

  - script: |
      cd $(Build.Repository.LocalPath)/CI && ./updatecoverage.sh
    env:
      COVERALLS_REPO_TOKEN: $(COVERALLS_REPO_TOKEN) # right way to map to an env variable
    displayName: 'Update coverage'
    condition: and(succeeded(), eq(variables['python.version'], '3.7'))
